/**
 * A self-signed P-256 certificate and its private key, used only by tests
 * that need a genuine x5c chain. Generated with openssl; not a secret.
 */
export const TEST_CERT_DER_B64 = "MIIBjDCCATOgAwIBAgIUZDFxklpZzhFhkn7v3rzQXUGvM7AwCgYIKoZIzj0EAwIwHDEaMBgGA1UEAwwRVkNETTIgVGVzdCBJc3N1ZXIwHhcNMjYwOTA3MTQ1MjMwWhcNMzYwOTA0MTQ1MjMwWjAcMRowGAYDVQQDDBFWQ0RNMiBUZXN0IElzc3VlcjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABB2S+GVme7arRRGtFk2KCxnQ7nVZVNEbehjTYkjPq0SJJr9mRLe/4pa0VQ3GzBMNZhe7b3WGVZHhOvQ8qziLHx6jUzBRMB0GA1UdDgQWBBTiSi+4rJqRwzLKq3popfaW+O2uUzAfBgNVHSMEGDAWgBTiSi+4rJqRwzLKq3popfaW+O2uUzAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0cAMEQCIGp4JPM6UXYNVMpgk0j/Clqa+StDw+MT64N4+YTM/+BwAiBK1+uyVi/yqOY3eif/qG4gqf13aSeyH+Q1olu+kh3hjQ==";

export const TEST_CERT_PEM = `-----BEGIN CERTIFICATE-----
${TEST_CERT_DER_B64}
-----END CERTIFICATE-----`;

export const TEST_PRIVATE_KEY_PKCS8_B64 = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQge5XveCpz7itSBk7RLktwN2dn+GMS5Db5luaU2q2ZAf2hRANCAAQdkvhlZnu2q0URrRZNigsZ0O51WVTRG3oY02JIz6tEiSa/ZkS3v+KWtFUNxswTDWYXu291hlWR4Tr0PKs4ix8e";

/** A second, unrelated self-signed certificate — a valid trust anchor that
 * the first certificate does not chain to. */
export const UNRELATED_CERT_DER_B64 = "MIIBijCCATGgAwIBAgIUGnkBj02CP1rj1VZff7R1hVA/seUwCgYIKoZIzj0EAwIwGzEZMBcGA1UEAwwQVW5yZWxhdGVkIEFuY2hvcjAeFw0yNjA5MDcxNDU0MjRaFw0zNjA5MDQxNDU0MjRaMBsxGTAXBgNVBAMMEFVucmVsYXRlZCBBbmNob3IwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASjb/60lNe2kxpZso81gH0Yv61AYkEhRTUCDi2txJv688uRODWqVbngSYouN9N5Mkollf9Tq/WVNSparv6sruh4o1MwUTAdBgNVHQ4EFgQULVlMXErPYHMLE8zt14VOQJkAXHwwHwYDVR0jBBgwFoAULVlMXErPYHMLE8zt14VOQJkAXHwwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNHADBEAiBaV7+Iyq1GXbFqjEDOhXCjAPNG6pSfS+GJiBsz3taGPAIgXOZAfF32vVFJLhVDHZ2l5iFgp2EYDpYZtRuXX0aYrXc=";

export const UNRELATED_CERT_PEM = `-----BEGIN CERTIFICATE-----
${UNRELATED_CERT_DER_B64}
-----END CERTIFICATE-----`;
