allowBuilds:
  cbor-extract: true
  esbuild: true
  sharp: true

patchedDependencies:
  cbor-x@1.6.4: patches/cbor-x@1.6.4.patch
  reactour@1.19.4: patches/reactour@1.19.4.patch

engineStrict: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@sirosfoundation/*'

## TEMPORARY fix: Override cbor-x version for @owf/cose dependency since
## @auth0/mdl and @owf/cose both depend on cbor-x and compete for its extensions
overrides:
  "@owf/cose>cbor-x": "1.6.5"

packages:
  - .
  - packages/*
  - crates/*
