/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface WalletFrontendEnvironmentConfiguration {
	/**
	 * Base path for asset loading. Used for sub-path deployments.
	 */
	BASE_PATH?: string;
	/**
	 * The installation's public URL.
	 */
	STATIC_PUBLIC_URL?: string;
	/**
	 * The installation's public name.
	 */
	STATIC_NAME?: string;
	/**
	 * Overrides translations of common.walletName.
	 */
	I18N_WALLET_NAME_OVERRIDE?: string;
	/**
	 * Redirect URI after authentication/token request at the authorization server in the OID4VCI flow.
	 */
	OPENID4VCI_REDIRECT_URI?: string;
	/**
	 * URL of the websocket service.
	 */
	WS_URL?: string;
	/**
	 * URL of the backend service.
	 */
	WALLET_BACKEND_URL: string;
	/**
	 * Engine URL for WebSocket transport. Falls back to WALLET_BACKEND_URL if unset.
	 */
	WALLET_ENGINE_URL?: string;
	/**
	 * Allowed transports (comma-separated in .env). 'direct' requires ecosystem CORS support.
	 */
	ALLOWED_TRANSPORTS?: ("websocket" | "direct")[];
	/**
	 * Transport preference order; first available wins.
	 */
	TRANSPORT_PREFERENCE?: ("websocket" | "direct")[];
	/**
	 * DID key version format (e.g. jwk_jcs-pub).
	 */
	DID_KEY_VERSION?: string;
	/**
	 * Browser console log level. WARNING: 'debug' may include sensitive data (JWTs/keys).
	 */
	LOG_LEVEL?: "error" | "info" | "warn" | "debug";
	/**
	 * WebAuthn relying party ID. Must match config.webauthn.rp.id in wallet-backend-server. Use 'localhost' locally.
	 */
	WEBAUTHN_RPID?: string;
	/**
	 * Proof type precedence for OID4VCI.
	 */
	OPENID4VCI_PROOF_TYPE_PRECEDENCE?: ("attestation" | "jwt")[];
	/**
	 * Verify the certificate SAN matches the response_uri in incoming OID4VP authorization requests.
	 */
	OPENID4VP_SAN_DNS_CHECK?: boolean;
	/**
	 * Toggle SAN validation of certificates during OpenID4VP.
	 */
	OPENID4VP_SAN_DNS_CHECK_SSL_CERTS?: boolean;
	/**
	 * Delegate trust evaluation to the backend AuthZEN proxy. Setting false is only allowed in development mode.
	 */
	DELEGATE_TRUST_TO_BACKEND?: boolean;
	/**
	 * Enable multi-language credential display. Empty is treated as false.
	 */
	MULTI_LANGUAGE_DISPLAY?: boolean;
	/**
	 * Fold history events older than this many seconds (default 30 days).
	 */
	FOLD_EVENT_HISTORY_AFTER_SECONDS?: number;
	/**
	 * Display the issuance warnings popup.
	 */
	DISPLAY_ISSUANCE_WARNINGS?: boolean;
	/**
	 * Maximum accepted batch size during an OpenID4VCI flow.
	 */
	OPENID4VCI_MAX_ACCEPTED_BATCH_SIZE?: number;
	/**
	 * Polling interval in seconds for transaction ID.
	 */
	OPENID4VCI_TRANSACTION_ID_POLLING_INTERVAL_IN_SECONDS?: number;
	/**
	 * Lifetime in seconds of transaction ID.
	 */
	OPENID4VCI_TRANSACTION_ID_LIFETIME_IN_SECONDS?: number;
	/**
	 * URL of the OHTTP key config endpoint.
	 */
	OHTTP_KEY_CONFIG?: string;
	/**
	 * URL of the OHTTP relay endpoint.
	 */
	OHTTP_RELAY?: string;
	/**
	 * URL of the Type Metadata registry for SD-JWT VC credentials.
	 */
	VCT_REGISTRY_URL?: string;
	/**
	 * TOS/policy links. In .env: LABEL::URL,LABEL::URL. Can be left blank.
	 */
	POLICY_LINKS?: {
		label: string;
		url: string;
	}[];
	/**
	 * Show the PWA installation prompt on the login screen.
	 */
	SHOW_PWA_INSTALL_PROMPT?: boolean;
	/**
	 * Enable integration with the Wallet Companion browser extension.
	 */
	WALLET_COMPANION_INTEGRATION?: boolean;
	/**
	 * Keep credentials in presentation history even after they are deleted from the wallet.
	 */
	PRESERVE_PRESENTATION_HISTORY?: boolean;
	/**
	 * Show the 'Scan Physical ID' entry point (native wrapper apps only) on the Add Credentials page.
	 */
	SCAN_PHYSICAL_ID_ENABLED?: boolean;
	/**
	 * Enable Wallet Instance Attestation.
	 */
	WIA_ENABLED?: boolean;
}
