export { verifyX5C } from './verifyX5C';
export { getSdJwtVcMetadata } from './getSdJwtVcMetadata';
export * from './util';
export { detectCredentialFormat, isMdoc, isSdJwt } from './detectCredentialFormat';
export * from './vcdm2';
export { detectCredentialFormat as detectFormat, isLdpVc } from './detectCredentialFormat';
export { canonicalizeJcs } from './dataIntegrity/jcs';
export { base58Decode, multibaseDecode, multikeyToJwk, didKeyToJwk } from './dataIntegrity/multibase';
export { createDocumentLoader, ALLOWED_CONTEXT_URLS } from './dataIntegrity/documentLoader';
export { verifyDataIntegrityProof, resolveCryptosuite, SupportedCryptosuites } from './dataIntegrity/verifyDataIntegrityProof';
export * from './vcdm2Presentation';
